name: "textlint"
on:
  pull_request:

jobs:
  textlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup node version
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "npm"
      - name: Install library
      - run: npm ci
      - name: Apply textlint --fix
      - run: npx textlint --fix

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3
          bundler-cache: true
      - run: bundle exec danger
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
